from pydantic import BaseModel, Field
from typing import List, Optional


class ExperienceItem(BaseModel):
    """
    Schema for a single professional work experience entry.
    """
    company: str = Field(..., description="The name of the company or organization")
    position: str = Field(..., description="The student's official job title or role")
    location: str = Field(..., description="City and State, or 'Remote'")
    duration: str = Field(..., description="The time frame of employment, e.g., 'June 2024 - Present'")
    highlights: List[str] = Field(..., description="Enhanced narrative bullet points")


class ProjectItem(BaseModel):
    """
    Schema for a single technical project entry.
    """
    title: str = Field(..., description="The name of the project")
    description: str = Field(
        ...,
        description="An engaging, 2-3 sentence narrative detailing the problem, solution, and impact"
    )

    tech_stack: List[str] = Field(
        ...,
        description="Programming languages and frameworks used"
    )

    github_url: Optional[str] = Field(
        None,
        description="Project repository URL if available"
    )


class EducationItem(BaseModel):
    """
    Schema for a single education entry.
    """
    institution: str = Field(..., description="The name of the school, college, or university")
    degree: str = Field(..., description="The degree or program, e.g., 'B.S. in Computer Science'")
    duration: str = Field(..., description="The time frame of study, e.g., 'Aug 2022 - May 2026'")
    details: Optional[str] = Field(
        None,
        description="Optional extra detail such as GPA, honors, or relevant coursework, only if present in the resume"
    )


class PortfolioProfile(BaseModel):
    """
    The master schema containing the fully parsed and enhanced portfolio dataset.
    """
    name: str = Field(..., description="The student's full name")
    headline: str = Field(..., description="A punchy, modern professional subtitle generated by the AI")
    email: str = Field(..., description="The extracted email address")
    github: Optional[str] = Field(None, description="The extracted GitHub profile URL, if present")
    linkedin: Optional[str] = Field(None, description="The extracted LinkedIn profile URL, if present")
    bio: str = Field(
        ...,
        description="A compelling, professional 3-4 sentence background narrative built by the AI"
    )

    experience: List[ExperienceItem] = Field(
        ...,
        description="Professional work experience entries"
    )

    projects: List[ProjectItem] = Field(
        ...,
        description="Technical project entries"
    )

    education: List[EducationItem] = Field(
        default_factory=list,
        description="Education entries such as degrees, schools, and graduation dates"
    )

    skills: List[str] = Field(
        ...,
        description="List of skills"
    )


if __name__ == "__main__":
    print("Testing schema module compilation...")

    try:
        print(PortfolioProfile.model_json_schema())
        print("\n[SUCCESS] Schema compiled perfectly and generated a valid JSON blueprint!")

    except Exception as e:
        print(f"\n[ERROR] Schema definition failed with error: {e}")